# Generated by Django 3.0.3 on 2020-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20200228_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='port',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
