# Generated by Django 3.0.3 on 2020-03-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_auto_20200304_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='type',
            field=models.CharField(choices=[('SSH', 'SSH'), ('FTB', 'FTB'), ('ADMIN', 'ADMIN'), ('EMAIL', 'EMAIL')], default='SELECT', max_length=255),
        ),
    ]
