# Generated by Django 3.0.3 on 2020-03-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20200304_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='type',
            field=models.CharField(choices=[('SSH', 'SSH'), ('FTB', 'FTB'), ('ADMIN', 'ADMIN'), ('EMAIL', 'EMAIL')], max_length=255),
        ),
    ]
