# Generated by Django 3.0.3 on 2020-03-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20200304_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
